version: "3.7"
services:
  bookmybird-app:
    container_name: bookmybird-app
    restart: unless-stopped
    build:
      context: .
      dockerfile: Containerfile
    volumes:
      - ./app:/usr/src/app
    environment:
      # See compose.override.TEMPLATE.yaml for additional env vars required.
      REQUEST_USER_AGENT: 'BookMyBird/1.0 (https://github.com/dennissiemensma/bookmybird)'
      LOCAL_TIMEZONE: 'Europe/Amsterdam'
